version: '3.8'

services:
  # Glyph API Service Definition
  backend:
    build:
      context: ./backend

    image: glyph_api_img:2.0
    container_name: glyph_api

    restart: always
    depends_on:
      - database

    env_file:
      - .env

    ports:
      - '${BACKEND_HOST_PORT:-5002}:5000'

    environment:
      - ENVIRONMENT=${ENVIRONMENT:-dev}
    
    command: yarn dev


  # Glyph Frontend Service Definition
  frontend:
    build:
      context: ./frontend

    image: glyph_client_img:1.0
    container_name: glyph_client

    restart: always
    depends_on:
      - backend

    ports:
      - '${FRONTEND_HOST_PORT:-5001}:3000'

    environment:
      - ENVIRONMENT=${ENVIRONMENT:-dev}

    command: yarn start


  # Database Container Service Definition
  database:
    image: mongo:4.2.8
    container_name: glyph_database

    restart: always

    ports:
      - '127.0.0.1:${MONGO_HOST_PORT:-27017}:27017'

    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb

    command: mongod


# Named Volume Definitions
volumes:
  mongodb:
  mongodb_config:

# Networks
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
       - subnet: 172.30.10.0/24